// Code generated by esmaq, DO NOT EDIT.
package myswitch

import (
	"context"
	"errors"
	esmaq "github.com/stevenferrer/esmaq"
)

type State esmaq.State

const (
	StateOff State = "off"
	StateOn  State = "on"
)

type Event esmaq.Event

const (
	EventSwitchOn  Event = "switchOn"
	EventSwitchOff Event = "switchOff"
)

type MySwitch struct {
	core *esmaq.Core
	cbs  *Callbacks
}

type Callbacks struct {
	SwitchOn  func(ctx context.Context) (err error)
	SwitchOff func(ctx context.Context) (err error)
}

func (sm *MySwitch) SwitchOn(ctx context.Context) (err error) {
	from, ok := fromCtx(ctx)
	if !ok {
		return errors.New("\"from\" state not set in context")
	}

	err = sm.core.Fire(esmaq.Event(EventSwitchOn), esmaq.State(from))
	if err != nil {
		return err
	}

	ctx = ctxWtTo(ctx, StateOn)

	err = sm.cbs.SwitchOn(ctx)
	if err != nil {
		return err
	}

	return nil
}

func (sm *MySwitch) SwitchOff(ctx context.Context) (err error) {
	from, ok := fromCtx(ctx)
	if !ok {
		return errors.New("\"from\" state not set in context")
	}

	err = sm.core.Fire(esmaq.Event(EventSwitchOff), esmaq.State(from))
	if err != nil {
		return err
	}

	ctx = ctxWtTo(ctx, StateOff)

	err = sm.cbs.SwitchOff(ctx)
	if err != nil {
		return err
	}

	return nil
}

func NewMySwitch(cbs *Callbacks) *MySwitch {
	stateConfigs := []esmaq.StateConfig{
		{
			From: esmaq.State(StateOff),
			Transitions: []esmaq.Transitions{
				{
					Event: esmaq.Event(EventSwitchOn),
					To:    esmaq.State(StateOn),
				},
			},
		},
		{
			From: esmaq.State(StateOn),
			Transitions: []esmaq.Transitions{
				{
					Event: esmaq.Event(EventSwitchOff),
					To:    esmaq.State(StateOff),
				},
			},
		},
	}

	mySwitch := &MySwitch{
		cbs:  cbs,
		core: esmaq.NewCore(stateConfigs),
	}

	return mySwitch
}

type ctxKey int

const (
	fromKey ctxKey = iota
	toKey
)

func CtxWtFrom(ctx context.Context, from State) context.Context {
	return context.WithValue(ctx, fromKey, from)
}

func ctxWtTo(ctx context.Context, to State) context.Context {
	return context.WithValue(ctx, toKey, to)
}

func fromCtx(ctx context.Context) (State, bool) {
	from, ok := ctx.Value(fromKey).(State)
	return from, ok
}

func ToCtx(ctx context.Context) (State, bool) {
	to, ok := ctx.Value(toKey).(State)
	return to, ok
}
