// Code generated by esmaq, DO NOT EDIT.
package main

import (
	"context"
	"errors"
	esmaq "github.com/stevenferrer/esmaq"
)

// State is the state type
type State esmaq.StateType

// String implements Stringer for State
func (s State) String() string {
	return string(s)
}

// List of state types
const (
	StateOn  State = "on"
	StateOff State = "off"
)

// Event is the event type
type Event esmaq.EventType

// String implements Stringer for Event
func (e Event) String() string {
	return string(e)
}

// List of event types
const (
	EventSwitchOff Event = "switchOff"
	EventSwitchOn  Event = "switchOn"
)

// ctxKey is a context key
type ctxKey int

// List of context keys
const (
	fromKey ctxKey = iota
	toKey
)

// Switch is a state machine
type Switch struct {
	core      *esmaq.Core
	callbacks *Callbacks
}

// Callbacks defines the state machine callbacks
type Callbacks struct {
	SwitchOff func(ctx context.Context) (err error)
	SwitchOn  func(ctx context.Context) (err error)
}

// Actions defines the state machine actions
type Actions struct {
	On  esmaq.Actions
	Off esmaq.Actions
}

// SwitchOff is a transition method for EventSwitchOff
func (sm *Switch) SwitchOff(ctx context.Context) (err error) {
	from, ok := fromCtx(ctx)
	if !ok {
		return errors.New("\"from\" is not set in context")
	}

	fromst, err := sm.core.GetState(castst(from))
	if err != nil {
		return err
	}

	tost, err := sm.core.Transition(castst(from), castet(EventSwitchOff))
	if err != nil {
		return err
	}

	// inject "to" in context
	ctx = ctxWtTo(ctx, StateOff)

	if sm.callbacks != nil && sm.callbacks.SwitchOff != nil {
		err = sm.callbacks.SwitchOff(ctx)
		if err != nil {
			return err
		}
	}

	if fromst.Actions.OnExit != nil {
		err = fromst.Actions.OnExit(ctx)
		if err != nil {
			return err
		}
	}

	if tost.Actions.OnEnter != nil {
		err = tost.Actions.OnEnter(ctx)
		if err != nil {
			return err
		}
	}

	return nil
}

// SwitchOn is a transition method for EventSwitchOn
func (sm *Switch) SwitchOn(ctx context.Context) (err error) {
	from, ok := fromCtx(ctx)
	if !ok {
		return errors.New("\"from\" is not set in context")
	}

	fromst, err := sm.core.GetState(castst(from))
	if err != nil {
		return err
	}

	tost, err := sm.core.Transition(castst(from), castet(EventSwitchOn))
	if err != nil {
		return err
	}

	// inject "to" in context
	ctx = ctxWtTo(ctx, StateOn)

	if sm.callbacks != nil && sm.callbacks.SwitchOn != nil {
		err = sm.callbacks.SwitchOn(ctx)
		if err != nil {
			return err
		}
	}

	if fromst.Actions.OnExit != nil {
		err = fromst.Actions.OnExit(ctx)
		if err != nil {
			return err
		}
	}

	if tost.Actions.OnEnter != nil {
		err = tost.Actions.OnEnter(ctx)
		if err != nil {
			return err
		}
	}

	return nil
}

// CtxWtFrom injects `from` state to context
func CtxWtFrom(ctx context.Context, from State) context.Context {
	return context.WithValue(ctx, fromKey, from)
}

// ctxWtTo injects 'to' state to context
func ctxWtTo(ctx context.Context, to State) context.Context {
	return context.WithValue(ctx, toKey, to)
}

// fromCtx retrieves 'from' state from context
func fromCtx(ctx context.Context) (State, bool) {
	from, ok := ctx.Value(fromKey).(State)
	return from, ok
}

// ToCtx retrieves 'to' state from context
func ToCtx(ctx context.Context) (State, bool) {
	to, ok := ctx.Value(toKey).(State)
	return to, ok
}

// NewSwitch is a factory for state machine Switch
func NewSwitch(callbacks *Callbacks, actions *Actions) *Switch {
	return &Switch{
		callbacks: callbacks,
		core: esmaq.NewCore([]esmaq.StateConfig{
			{
				From:    castst(StateOn),
				Actions: actions.On,
				Transitions: []esmaq.TransitionConfig{
					{
						Event: castet(EventSwitchOff),
						To:    castst(StateOff),
					},
				},
			},
			{
				From:    castst(StateOff),
				Actions: actions.Off,
				Transitions: []esmaq.TransitionConfig{
					{
						Event: castet(EventSwitchOn),
						To:    castst(StateOn),
					},
				},
			},
		}),
	}
}

// castst casts State to esmaq.StateType
func castst(s State) esmaq.StateType {
	return esmaq.StateType(s)
}

// castet casts Event to esmaq.EventType
func castet(e Event) esmaq.EventType {
	return esmaq.EventType(e)
}
